### ISSUE TITLE
Needed to edit CMakeLists to make bpp-seq-omics

### ISSUE THREAD

**Issue by andrewSharo** [BioPP/bpp-seq-omics#11]
I was running into the following error while running 'make':

/h/andrewsharo/.local/include/Bpp/Numeric/Table.h: In static member function ‘static std::unique_ptr<bpp::Table<T> > bpp::Table<T>::read(std::istream&, bool, const string&, bool, int)’:
/h/andrewsharo/.local/include/Bpp/Numeric/Table.h:1059:19: error: ‘make_unique’ is not a member of ‘std’
dt = std::make_unique< Table<T> >(0, nCol);

I found that this error was resolved by editing line 12 of CMakeLists.txt from:

set (CMAKE_CXX_FLAGS "-std=c++11 -Wall -Weffc++ -Wshadow -Wconversion")
to
set (CMAKE_CXX_FLAGS "-std=c++14 -Wall -Weffc++ -Wshadow -Wconversion")

Not sure if this was just an issue with my environment, but posting here in case others have this issue. I had to do the same to get bpp-phyl-omics to install as well.

**Comment by lgueguen** [comment]
Indeed, this is fixed.

Cheers,
Laurent
